name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install OpenGL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y freeglut3-dev libglew-dev libglfw3-dev mesa-utils build-essential cmake
      - name: Build binaries for library
        run: cargo build --lib
  test-lib:
    runs-on: ubuntu-latest
    needs: build-lib
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test library
        run: cargo test
