name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install OpenGL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglfw3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev xorg-dev
          sudo apt-get install -y xvfb
      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Set DISPLAY environment variable
        run: echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Build binaries for library
        run: cargo build --lib --release
  test-lib:
    runs-on: ubuntu-latest
    needs: build-lib
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test library
        run: cargo test --release
